[package]
name = "iter-rat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1.45"
num-rational = "0.4.1"
num-traits = "0.2.15"
